# scrutinizer-ci.com configuration
# language: python
imports:
    - python

build:
    environment:
        python: 3.6.3
    tests:
        before:
            - 'python setup.py install'
            - 'pip install "python-dotenv>=0.7.1"'
            - 'pip install "Pillow>=5.0.0"'
            - 'pip install "requests_mock>=1.4.0"'
            - 'pip install nose-exclude'
        override:
            -
                command: 'nosetests --exclude-dir=tests/custom'

checks:
    python:
        code_rating: true
        duplicate_code: true
        classes_valid_slots: true