# scrutinizer-ci.com configuration

# language: python
imports:
    - python

build:
    environment:
        python: 3.6.3

checks:
    python:
        duplicate_code: true
        code_rating: true
        classes_valid_slots: true

before_commands:
    - pip install .
    - pip install .[unittests]
