language: python
sudo: false

python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3"  # Pypy3 5.8.0-beta0

# command to install dependencies
install:
  - pip install .
  - pip install .[unittests]
  - pip install codecov

script:
  - coverage run tests/files/test_constraint.py
  - coverage run tests/files/test_filehandler.py
  - coverage run tests/files/test_filter.py

after_success:
  - codecov