language: python
sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev" # 3.8 development branch
  - "nightly" # nightly build
  # PyPy versions
  - "pypy3"

matrix:
  allow_failures:
    - python: nightly

install:
  - python setup.py install
  - pip install 'python-dotenv>=0.7.1'
  - pip install 'Pillow>=5.0.0'
  - pip install 'requests_mock>=1.4.0'
  - pip install nose-exclude
  - pip install coveralls

script:
  - nosetests --exclude-dir=tests/custom --with-coverage --cover-package=saucenao

after_success:
  - coveralls